// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkM5tIPHsX4muahQc0tqkUvidPt-iPtoM',
    appId: '1:616085059336:web:baebcf01ab106b64809ebd',
    messagingSenderId: '616085059336',
    projectId: 'nodelabs-d0e62',
    authDomain: 'nodelabs-d0e62.firebaseapp.com',
    storageBucket: 'nodelabs-d0e62.firebasestorage.app',
    measurementId: 'G-FJY36P9R98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3A-wMshZqMK4KvAbdw0_tSsFALG1C6pA',
    appId: '1:616085059336:android:61bac029d06299a5809ebd',
    messagingSenderId: '616085059336',
    projectId: 'nodelabs-d0e62',
    storageBucket: 'nodelabs-d0e62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMD-JvZA0QY_S6ttctWBRqeArGseG64ao',
    appId: '1:616085059336:ios:f7faf7e7b7c0e257809ebd',
    messagingSenderId: '616085059336',
    projectId: 'nodelabs-d0e62',
    storageBucket: 'nodelabs-d0e62.firebasestorage.app',
    iosBundleId: 'com.emtay.architecture.architectureTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMD-JvZA0QY_S6ttctWBRqeArGseG64ao',
    appId: '1:616085059336:ios:f7faf7e7b7c0e257809ebd',
    messagingSenderId: '616085059336',
    projectId: 'nodelabs-d0e62',
    storageBucket: 'nodelabs-d0e62.firebasestorage.app',
    iosBundleId: 'com.emtay.architecture.architectureTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkM5tIPHsX4muahQc0tqkUvidPt-iPtoM',
    appId: '1:616085059336:web:a7c83b4c62b678fd809ebd',
    messagingSenderId: '616085059336',
    projectId: 'nodelabs-d0e62',
    authDomain: 'nodelabs-d0e62.firebaseapp.com',
    storageBucket: 'nodelabs-d0e62.firebasestorage.app',
    measurementId: 'G-6Z1MJGM6V4',
  );
}
